// Movie actions

export const FILTER_MOVIE = 'FILTER_MOVIE';
export const STORE_SEARCHITEM = 'STORE_SEARCHITEM';
export const DELETE_SEARCHITEM = 'STORE_SEARCHITEM';
export const ADDMOVIETOFAVORITES = 'ADDMOVIETOFAVORITES';
export const DELETEMOVIEFROMFAVORITES = 'DELETEMOVIEFROMFAVORITES';

// Popup actions

export const OPEN_MODAL = 'OPEN_MODAL';
